# cmail fish completion. Place in ~/.config/fish/completions/cmail.fish.
complete -c cmail -f
# Old-style single-letter flags prevent suggestions of unsupported bundled flags.
complete -c cmail -o h -l help -d 'Show help'
complete -c cmail -o V -l version -d 'Print version'
complete -c cmail -o c -l config -r -F -d 'Select private configuration'
complete -c cmail -o f -l format -x -a 'text json' -d 'Report format'
complete -c cmail -o v -l verbose -d 'Redacted diagnostics'
complete -c cmail -o q -l quiet -d 'Suppress progress'
complete -c cmail -l no-color -d 'Disable color'
complete -c cmail -l no-browser -d 'Print manual links'
complete -c cmail -l timeout -x -d 'HTTP timeout in seconds'
complete -c cmail -n 'not __fish_seen_subcommand_from setup status doctor send-as config completion help' -a 'setup status doctor send-as config completion help'
complete -c cmail -n '__fish_seen_subcommand_from setup' -l domain -x -d 'Domain name'
complete -c cmail -n '__fish_seen_subcommand_from setup' -l destination -x -d 'Receiving email'
complete -c cmail -n '__fish_seen_subcommand_from setup' -l addresses -x -d 'Comma-separated aliases'
complete -c cmail -n '__fish_seen_subcommand_from setup' -l registrar -x -a 'manual godaddy' -d 'Registrar handling (default manual)'
complete -c cmail -n '__fish_seen_subcommand_from setup' -l dry-run -d 'Read-only setup preview'
complete -c cmail -n '__fish_seen_subcommand_from setup' -l wait-timeout -x -d 'Activation or verification wait limit'
complete -c cmail -n '__fish_seen_subcommand_from doctor' -l offline -d 'Local checks only'
complete -c cmail -n '__fish_seen_subcommand_from config; and not __fish_seen_subcommand_from init show check set path' -a 'init show check set path'
complete -c cmail -n '__fish_seen_subcommand_from config; and __fish_seen_subcommand_from set' -l stdin -d 'Read one setting from stdin'
complete -c cmail -n '__fish_seen_subcommand_from config; and __fish_seen_subcommand_from set; and not __fish_seen_subcommand_from DOMAIN DEST_EMAIL ADDRESSES REGISTRAR GDDY_ENV CF_ZONE_ID CF_ACCOUNT_ID DRY_RUN CLOUDFLARE_API_TOKEN GDDY_PAT' -a 'DOMAIN DEST_EMAIL ADDRESSES REGISTRAR GDDY_ENV CF_ZONE_ID CF_ACCOUNT_ID DRY_RUN CLOUDFLARE_API_TOKEN GDDY_PAT'
complete -c cmail -n '__fish_seen_subcommand_from completion; and not __fish_seen_subcommand_from bash zsh fish' -a 'bash zsh fish'
